"""update May 30

Revision ID: 3d1325ab9569
Revises: 417b40879b86
Create Date: 2016-05-30 16:18:51.205353

"""

# revision identifiers, used by Alembic.
revision = '3d1325ab9569'
down_revision = '417b40879b86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), default='默认标题'))
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
