"""add generate

Revision ID: 417b40879b86
Revises: None
Create Date: 2016-05-25 19:13:25.401570

"""

# revision identifiers, used by Alembic.
revision = '417b40879b86'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('link_name', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'link_name')
    ### end Alembic commands ###
